#!/bin/bash

# Starting some programs before bspwm
pgrep -x sxhkd > /dev/null || sxhkd & # start sxhkd if not already running
. $HOME/.config/bspwm/scripts/eww.sh  # start eww
~/.fehbg &                            # set wallpaper
xsetroot -cursor_name left_ptr &      # set cursor
picom --animations -b &               # start picom (ftlabs fork)

bspc monitor -d 1 2 3 4 5

bspc config border_width            2
bspc config window_gap              5
bspc config focused_border_color    "#bfc9db"

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config top_padding             50
